name: E2E Docker Proxy Nginx Test

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    # run every sunday
    - cron: '0 0 * * 0'
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Start containers
      run: docker-compose -f "./docker/proxy-nginx/docker-compose.yaml" up -d --build

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install verdaccio cli
      run: npm install -g verdaccio --registry=http://localhost:4873

    - name: Stop containers
      if: always()
      run: docker-compose -f "./docker/proxy-nginx/docker-compose.yaml" down