name: E2E Docker Proxy Test

on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    # run every sunday
    - cron: '0 0 * * 0'
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install -g verdaccio --http://localhost:4873

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down