name: Docker Smoke Test
on:
  workflow_dispatch:
  pull_request:
  push:
  # schedule:
    # run every sunday
    # - cron: '0 0 * * 0'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio
            docker run --network container:verdaccio appropriate/curl --retry 10 --retry-connrefused http://localhost:4873/ping