name: Docker Smoke Test
on:
  workflow_dispatch:
  pull_request:
  push:
  # schedule:
    # run every sunday
    # - cron: '0 0 * * 0'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: 18.x    
      - name: Docker test
        run: |
            docker run -d -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio
            npm ping verdaccio